### ISSUE TITLE
Application needs to shutdown both clients to end.

### ISSUE THREAD

**Issue by mateusduboli** [poweld/hipchat-scala#20]
I'm executing a Spark job which generates a output to HipChat.

After the notification is send the application continues to run, even though my code has finished.

Using `visual-vm` I've found that the threads from `dispatch` are kept alive, making the application wait for them to finish.

Here's an [example gist](https://gist.github.com/mateusduboli/c0391f6d4fceb99bd7d5138503108526) to reproduce the bug.

To solve this I added a callback finishing the internal dispatch clients, enabling the application to die.

```scala
eventualNotification.onComplete { _ =>
  // Both clients are needed, only one or the other doesn't work
  Http.shutdown()
  Common.http.shutdown()
} 
```

This is IMO a severe bug, since my application needs to handle the lifecycle of the internal http library of one of my dependencies.

One suggestion is to choose another http client, I've had used `dispatch` before and had a terrible experience with it on a similar scenario.

**Comment by poweld** [comment]
Patch applied in version `1.1`
